### PR TITLE
Add legacy async helpers back in

### PR DESCRIPTION
**Pull request by wied03**
@elia - Let me know if my messaging was off. I tried to help people decide what to use.

### CODE REVIEW

**Comment by elia** [comment]
Great! :+1:

**Comment by wied03** [comment]
@elia - What's your thoughts on when to do a new release of opal-rspec to Rubygems?

**Comment by elia** [comment]
@wied03 As soon as I take the time to do it, but maybe we can delay after updating to rspec v3.3, you have any preference about that?

**Comment by wied03** [comment]
@elia - Guess it depends on what release process you like to follow (e.g. if you want to do any additional soak testing, etc.) and how onerous that process is. Given 0.4.3 is based on that old beta, I'd say put 'master' out as a release now so that people can take advantage of it, and then work on on 3.2, 3.3, etc.

**Comment by elia** [comment]
Released 0.5 beta1, will try it on opal rails and on my current app at work before going for the final release.

**Pull request merged**
