### PR TITLE
Promise Based Async Support – reprise (thanks to @wied03!)

### PR DESCRIPTION
**Pull request by elia**
fixes #21

cc @wied03 @ryanstout @adambeynon

### CODE REVIEW

**Comment by ryanstout** [comment]
awesome, thanks everyone!

**Comment by elia** [comment]
@wied03 I rebased against master and it's ready to merge :tada: 

Before that I have a question: is it necessary to remove the old async stuff that @adambeynon did?
If not I'd rather prefer to keep it as some apps could depend on it (and I also kinda liked the `async` name :wink:).

cc @adambeynon @ryanstout

**Comment by wied03** [comment]
@elia and @adambeynon - Maybe. One way would be to just make 'async' an alias for 'it', then 'run_async' becomes an alias for delay_with_promise(0)

**Comment by elia** [comment]
Still need to wrap my head around the new async stuff but sounds good, I'll merge. Can you send after I merge a PR that adds back those methods along with a note in the README and CHANGELOG?

Btw the tests (as in `rake test`) are much better now, thanks!

**Comment by wied03** [comment]
Yep

**Pull request merged**
