### PR TITLE
Promise Based Async Support

### PR DESCRIPTION
**Pull request by wied03**
Builds on the Opal 0.8/RSpec 3.1 branch/pull request.

I've updated the README and Changelog to show usage but here is what has changed on a more detailed level:

* Added a basic Rake task that wraps the opal:spec test and ensures that we fail when we're supposed to and checks to make sure the right tests failed. This is kind of rudimentary I know, but before this, there was no way to verify that opal-rspec was failing when it should
* Async support
 * Example group hierarchy
 * Pending/skipped within the example
 * Before/after each
 * Around example
 * Test failures show up properly in results instead of uncaught exceptions
* Added/organized lots of other specs to try and prevent regression as the async changes were made

### CODE REVIEW

**Comment by wied03** [comment]
@elia  - will be happy to squash if you like what you see here. I can also redo the PR if/when the 3.1/0.8 PR is merged in so that it's easier to see just the async changes.

**Comment by elia** [comment]
Let's do it this way: squash the commits on #19 and I'll push it as a new rspec31 branch (or something similar) the this PR can target that branch instead of master and the real diff becomes intelligible. Sounds good?

**Comment by wied03** [comment]
@elia  - done

**Comment by ryanstout** [comment]
Any updates on this?  I could use this merged if it looks good.  Nice work @wied03

**Comment by elia** [comment]
It's next on my list (the whole repo) but needing more than 5min of attention I keep delaying it. 😕

**Comment by ryanstout** [comment]
@elia cool, no rush.  Keep up the good work.

**Pull request closed without merging**
